# Generated by Django 4.1 on 2022-09-01 12:19

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_comments_options_alter_groups_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='body'),
        ),
    ]
