# Generated by Django 4.1 on 2022-09-08 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, null=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('stop_date', models.DateTimeField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group')),
                ('poll_option_1', models.ManyToManyField(related_name='poll_1', to=settings.AUTH_USER_MODEL)),
                ('poll_option_2', models.ManyToManyField(related_name='poll_2', to=settings.AUTH_USER_MODEL)),
                ('poll_option_3', models.ManyToManyField(related_name='poll_3', to=settings.AUTH_USER_MODEL)),
                ('poll_option_4', models.ManyToManyField(related_name='poll_4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('is_admin_notification', models.BooleanField(default=False)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group')),
                ('user', models.ManyToManyField(related_name='notification_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('time_start', models.DateTimeField(null=True)),
                ('time_end', models.DateTimeField(null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_started', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group')),
                ('maybe', models.ManyToManyField(related_name='event_maybe', to=settings.AUTH_USER_MODEL)),
                ('no', models.ManyToManyField(related_name='event_no', to=settings.AUTH_USER_MODEL)),
                ('yes', models.ManyToManyField(related_name='event_yes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
