# Generated by Django 4.1 on 2022-09-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_posts_options_alter_likes_is_active_and_more'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-time_stamp',)},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='poll_option_1',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='poll_option_2',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='poll_option_3',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='poll_option_4',
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_option',
            field=models.JSONField(default=dict, help_text='Maximum of 4 Options'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='maybe',
        ),
        migrations.RemoveField(
            model_name='event',
            name='no',
        ),
        migrations.RemoveField(
            model_name='event',
            name='yes',
        ),
        migrations.AlterField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group'),
        ),
        migrations.AddField(
            model_name='event',
            name='maybe',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='no',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='yes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
