# Generated by Django 4.1 on 2022-08-31 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_comments_options_alter_groups_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('time_start', models.DateTimeField(null=True)),
                ('time_end', models.DateTimeField(null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_started', models.BooleanField(default=False)),
                ('yes', models.JSONField(default=list)),
                ('no', models.JSONField(default=list)),
                ('maybe', models.JSONField(default=list)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.groups')),
            ],
        ),
        migrations.AddField(
            model_name='polls',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polls',
            name='stop_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polls',
            name='polls_option',
            field=models.JSONField(default=dict, help_text='Maximum of 4 Options'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
