# Generated by Django 4.1 on 2022-08-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_events_polls_start_date_polls_stop_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='maybe',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='no',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='yes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
