# Generated by Django 4.1 on 2022-09-11 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_posts_options_alter_likes_is_active_and_more'),
        ('activities', '0002_alter_notification_options_remove_poll_poll_option_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.CharField(max_length=500),
        ),

    ]
