# Generated by Django 4.1 on 2022-09-07 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_posts_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0003_alter_events_maybe_alter_events_no_alter_events_yes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Polls',
            new_name='Poll',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='polls_option',
            new_name='poll_option',
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_admin_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
