# Generated by Django 4.1 on 2022-09-15 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_posts_options_alter_likes_is_active_and_more'),
        ('activities', '0003_alter_event_options_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(help_text='Kindly input the question', max_length=90, null=True),
        ),

    ]
