# Generated by Django 4.1 on 2022-09-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_posts_options_alter_likes_is_active_and_more'),
        ('activities', '0003_alter_event_options_alter_event_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.members')),
            ],
        ),
    ]
