# Generated by Django 4.1 on 2022-09-15 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_posts_options_alter_likes_is_active_and_more'),
        ('activities', '0004_event_date_end_event_date_start_alter_event_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),

    ]
