# Generated by Django 4.0.6 on 2022-08-28 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_comments_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
